# Generated by Django 6.0.7 on 2026-07-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='num_reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
